version: '1.0'
services:
  db:
    image: postgres
    restart: always
    build: 
      dockerfile: ./DockerFile
    volumes:
      - ./resources/db-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'raftmodding'
    ports:
      - '5432:5432'
    expose:
      - '5432'