name: Node CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: npm install
        run: npm install
      - name: npm run build
        run: npm run build --if-present
      - name: npm run test
        run: npm run test --if-present
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY_VPS_NEW }}
          port: ${{ secrets.REMOTE_PORT }}
          script: cd ${{ secrets.REMOTE_DEPLOY_PATH }} && git stash push --include-untracked && git stash drop && git pull && npm ci && npm run build && cd ${{ secrets.REMOTE_WORK_DIR }} && pm2 stop ${{ secrets.REMOTE_APP_NAME }} && pm2 start