name: Node CI

on:
  push:
    branches:
      - main

jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: Install Node.js
#        uses: actions/setup-node@v1
#        with:
#          node-version: '16.x'
#      - name: npm install
#        run: npm install
#      - name: npm run build
#        run: npm run build --if-present
#      - name: npm run test
#        run: npm run test --if-present

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            # init nvm
            export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")" 
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            # set node version
            nvm use 16
            # pull repo
            cd /srv/hmodding.com/app/web-monorepo
            git pull origin main
            # build app
            npm ci
            npm run build
            cd /srv
            # start app daemon
            pm2 start hmodding.com
        # Additional commands for your specific setup
