name: Node CI

on:
  push:
    branches:
      - main

jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: Install Node.js
#        uses: actions/setup-node@v1
#        with:
#          node-version: '16.x'
#      - name: npm install
#        run: npm install
#      - name: npm run build
#        run: npm run build --if-present
#      - name: npm run test
#        run: npm run test --if-present

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /srv/hmodding.com/app/web-monorepo
            git pull origin main
            ~/.nvm/versions/node/v16.17.0/bin/npm ci
            ~/.nvm/versions/node/v16.17.0/bin/npm run build
            cd /srv
            ~/.nvm/versions/node/v16.17.0/bin/pm2 start hmodding.com
        # Additional commands for your specific setup
