name: Node CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: npm install
        run: npm install
      - name: npm run build
        run: npm run build --if-present
      - name: npm run test
        run: npm run test --if-present